sudo: required
language: node_js
notifications:
  email: george.contaot@gmail.com
node_js:
  - 10.15.3
services:
  - postgresql
env:
  global:
    - NODE_ENV: test
    - TRAVIS: true
  addons:
    postgresql: '11.3'
  before_script:
    - psql -c 'create database ts_api_test;' -U postgres
    - npm i -g sequelize-cli gulp-cli
    - cd server/
    - sequelize db: migrate --env test
    - npm install
    - gulp
    script:
    - npm rum unit-test
    - npm rum integration-test
